import { ReviewType } from "@/types";
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.NEXT_PUBLIC_OPEN_AI_API_KEY || "",
  dangerouslyAllowBrowser: true,
});

const keyWordAnalyzer = async (content: string) => {
  console.log("welcome to openAI fetching keywords");
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "system",
          content:
            "You will be provided with an array of reviews, and your task is to extract keywords from it.",
        },
        {
          role: "system",
          content: "Provide only top 10 most frequent keywords and they should be comma separated ",
        },
        {
          role: "user",
          content,
        },
      ],
      temperature: 0.5,
      max_tokens: 256,
      top_p: 1,
      frequency_penalty: 0,
      presence_penalty: 0,
    });
    console.log({ response });
    const keyword = response?.choices[0]?.message?.content || "";
    return keyword;
  } catch (error) {
    console.log(error);
    throw new Error("error");
  }
};

const getAllKeywords = async (reviews: ReviewType[]) => {
  const reviewsArray = reviews.map(({ content }) => content);
  const keywords = await keyWordAnalyzer(JSON.stringify(reviewsArray));
  console.log("Keywords Generated By Open AI", { keywords });
  // Get the top 10 keywords
  const top10Keywords = keywords
    .split(",")
    .slice(0, 10)
  return top10Keywords;
};

export default getAllKeywords;
